.TH goodbye 1 2011-07-28 goodbye goodbye
.SH NAME
goodbye \- the counterpart to 'Hello world'
.SH SYNOPSIS
.B goodbye
.SH DESCRIPTION
.B goodbye
is a tool that decrypts a fixed message using military-grade double ROT13
encryption and prints it to the screen.  Seriously though, this is a
packaging example, not meant to do anything useful on its own.
.SH "SEE ALSO"
.BR hello ( 1 ).
